version: '3'

services:
  disneytable:
    build:
      context: .
    container_name: disneytable
    restart: unless-stopped
    # ports: 
    #   - '8080:8080'
    environment:
      - API_KEY=${API_KEY}
      - DISNEY_USERNAME=${DISNEY_USERNAME}
      - DISNEY_PASSWORD=${DISNEY_PASSWORD}
    volumes:
      - ./data:/data